### ISSUE TITLE
Create external and internal documentation

### ISSUE THREAD

**Issue by shashank136** [haxxorsid/referralboard#10]
## Description
As a user, I would like to have an external (user interface/frontend) documentation to understand how the UI should be used. Add details about the implementation of the frontend with mock-up screens and explain the user interaction.

As a developer, I would like to have internal API documentation to understand API request and responses for the different end points. Add backend API documentation and explain how to use the exposed API.

As a project review and a developer, I would like to have a document on branching strategy and rules being followed.

All these should be documented in the wiki. README must have the links to this wiki and content of README can be moved to a "Home/About" page in Wiki.

## Acceptance Criteria
- [x] Add images for Edit Screen
- [x] Add images for User registration Screen
- [x] Add documentation for Edit screen
- [x] Add documentation for User registration Screen
- [x] Add images for Login Screen
- [x] Add images for Home Screen
- [x] Add image for navbar
- [x] Add documentation for Login screen
- [x] Add documentation for Home Screen
- [x] Add documentation for User table API end points
- [x] Add documentation for Post table API end points
- [x] Add documentation for branching strategy.
- [x] Add wiki links to README.
- [x] Move README content to a "Home/About" page in wiki.

**Comment by haxxorsid** [comment]
API Documentation by @shashank136 - [here](https://github.com/haxxorsid/referralboard/wiki/API-Reference)
Frontend Documentation by @bahetianjali @shashank136 @Vineetkhadloya - [here](https://github.com/haxxorsid/referralboard/wiki/Frontend-Documentation)
Branching strategy by @haxxorsid - [here](https://github.com/haxxorsid/referralboard/wiki/Branching-Strategy)

**Comment by shashank136** [comment]
I have updated the frontend documentation to house both the Edit screen and Registration screen for the UI part. @bahetianjali you can start modifying them as per our further needs.

**Comment by haxxorsid** [comment]
thanks. updated my comment @shashank136 .
