### ISSUE TITLE
Create UI for User registration

### ISSUE THREAD

**Issue by bahetianjali** [haxxorsid/referralboard#15]
## Description:

As a user, I want to be able to register so that I can log in whenever I want to create a post for getting a referral. Registration is the first step at the user's end to be able to get the referral. 
The details needed should be:
1. First Name
2. Last Name
3. Current Location
4. Current Company Name
5. Current Position Title
6. University
7. Years of Experience
8. Email Address
9. Password

After the user fills in the right information there should be a register button so that all the information gets passed to the database and then the user can log in with the set of credentials. 

## Acceptance Criteria:
-	[x] The registration page should be accessible from the “/register” path.
-	[x] The page must have a registration form.
-	[x] The login form should have a First name address field with the string data type.
-	[x] The login form should have a Last name address field with the string data type.
-	[x] The login form should have a Current Location address field with the string data type.
-	[x] The login form should have a Current Company Name field with the string data type.
-	[x] The login form should have a University field with the string data type.
-	[x] The login form should have a Years of Experience dropdown with the number data type.
-	[x] The login form should have a Password field with the string data type.
-	[x] There should be a back-to-login form link below the login form.

**Comment by bahetianjali** [comment]
@haxxorsid @shashank136 @Vineetkhadloya Please check if everything is up to the mark

**Comment by shashank136** [comment]
@bahetianjali Can you mention the expected data type for each field in the form

**Comment by bahetianjali** [comment]
> @bahetianjali Can you mention the expected data type for each field in the form

Done @shashank136 please check

**Comment by haxxorsid** [comment]
@bahetianjali  add "projects" as Sprint1.
