### ISSUE TITLE
Create tables with dummy data

### ISSUE THREAD

**Issue by shashank136** [haxxorsid/referralboard#16]
As a developer, I want to have a database populated with dummy data for the user table, Post table, and company table.

The user table should have the following fields:

- User ID (Primary Key)  - Integer
- First Name - String 
- Last Name - String
- Email - String
- Organization - String
- Title - String
- Password - String
- Current Location - String
- Current Company name - String
- Current Company ID - Integer
- Years of Experience Id- Integer

The Post table should have the following fields:

- Post Id (Primary Key) - Integer
- User Id (Foreign Key) - Integer
- Job link - String
- Target Company Id - Integer
- Target position - String
- About user - String
- Title - String
- Resume link - String

The Company table should have the following fields:

- Company Id (Primary Key) - Integer
- Company Name - String
- company email extension  - String

The Years_of_experience table should have the following fields:

- Years of Experience Id (Primary key) - Integer
- Description - String

Acceptance criteria:

- [x] Create User table with required fields as mentioned in the user story
- [x] Create Post table with required fields as mentioned in the user story
- [x] Create Company table with the required field as mentioned in the user story

**Comment by haxxorsid** [comment]
@shashank136 better title will be create user, post, company tables instead of populating database.

**Comment by haxxorsid** [comment]
@shashank136 add years_of_experience table
