### ISSUE TITLE
Expose API for POST table

### ISSUE THREAD

**Issue by shashank136** [haxxorsid/referralboard#18]
As a Frontend Developer, I want to receive all the Posts created properly formatted in JSON format.

As a Frontend Developer, I want to update the Post create with the required fields using JSON format.

As a Frontend Developer, I want to delete a Post using an HTTP request.

Acceptance Criteria:

- [x] Expose API to GET all Post tables.
- [x] Expose API to Update the Post from the table. 
- [x] Expose API to delete a Post from table

**Comment by haxxorsid** [comment]
@shashank136 we are not updating posts for now. "date a POST"? In title and description, Write "POST" table in small caps as "post". 

Add labels, projects, and assign this to yourself.
