### ISSUE TITLE
Create UI for edit profile

### ISSUE THREAD

**Issue by bahetianjali** [haxxorsid/referralboard#19]
## Description:

As a user, I want to be able to edit the profile. If by mistake the user enters the wrong first name or last name, the user should be able to change. If the user moves to another location, he/ she should be able to update. If the user changes the company or the user's title has changed, he/ she should be able to update the same by editing his/ her profile. Similarly, the years of experience, email address, and password should also be editable. 
The editable details include:
1. First Name
2. Last Name
3. Current Location
4. Current Company Name
5. Current Position Title
6. University
7. Years of Experience
8. Email Address
9. Password

After the user fills in the information he/ she needs to update then there should be a button that says save changes.

As an user, I want a navbar to be visible on this page's top with the name of the website, home page button (#17), requests button, edit profile page button, a green post button, and a logout button.

The dummy page created in #7 for fetching cards data, can be moved to "/home" path and fetch Posts data via API in #18 .

## Acceptance Criteria:
-	[x] The edit profile page should be accessible from the “/edit-profile” path.
-	[x] The form should be prefilled with the previous data and should be editable. 
-	[x] The page must have the same form as the registration form and the form fields should be editable.
- [x] Create a navbar component and display the navbar at the top of the page.
- [x] Move dummy page to "/home" and fetch Posts data.

**Comment by bahetianjali** [comment]
@shashank136 @Vineetkhadloya @haxxorsid please check

**Comment by haxxorsid** [comment]
@bahetianjali  add labels, projects, assign this to yourself.
