### ISSUE TITLE
Create UI for Forgot Password

### ISSUE THREAD

**Issue by bahetianjali** [haxxorsid/referralboard#20]
## Description:
The user should be able to log back in if he has forgotten his/ her password. Ther is a field of the email address that the user has to fill up. There should be a button with a reset password in the form and the user should be able to go back to the login page and the registration page from that forgot password page. 

## Acceptance Criteria:
-	[ ] The forgot password should be accessible from the “/forgot-password” path.
-	[ ] The form should have a reset password button on it. 
-	[ ] The page must have links that allow users to go back to the login and the registration page.

**Comment by bahetianjali** [comment]
@haxxorsid Please check

**Comment by shashank136** [comment]
@bahetianjali forgot/reset password feature can be handled in later sprints

**Comment by shashank136** [comment]
For sprint 1 we can just leave a dummy button with no action linked when clicked. Moved the issue to the backlog.
