### ISSUE TITLE
Setup step is missing the steps to create the sample db, tables and the sequences. 

### ISSUE THREAD

**Issue by ramesharun** [haxxorsid/referralboard#61]
**Describe the bug**
Referring user story #10 -  Setup Wiki for the server is missing the steps to create the postgres db, tables required and the sequence that need to be created before executing the server. Currently it fails with the below error : 
go run main.go
go: downloading gorm.io/driver/postgres v1.2.3
go: downloading gorm.io/gorm v1.22.5
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/jackc/pgx/v4 v4.14.1
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/jinzhu/now v1.1.4
go: downloading github.com/jackc/pgconn v1.10.1
go: downloading github.com/jackc/pgtype v1.9.1
go: downloading github.com/jackc/pgproto3/v2 v2.2.0
go: downloading github.com/jackc/pgio v1.0.0
go: downloading github.com/jackc/chunkreader/v2 v2.0.1
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b
go: downloading golang.org/x/crypto v0.0.0-20220112180741-5e0467b6c7ce

2022/02/15 22:43:47 /Users/rarunachalam/ramesh/tools/referralboard/server/app/app.go:37
[error] failed to initialize database, got error failed to connect to `host=localhost user=postgres database=appdb`: server error (FATAL: database "appdb" does not exist (SQLSTATE 3D000))
panic: failed to connect to `host=localhost user=postgres database=appdb`: server error (FATAL: database "appdb" does not exist (SQLSTATE 3D000))

**To Reproduce**
1. cd server && go run main.go

**Expected behavior**
Server is expected to start

**Comment by haxxorsid** [comment]
@ramesharun 
Updated [Setup wiki page](https://github.com/haxxorsid/referralboard/wiki/Setup). Refer point 2 and 3 under **Start server**. 

You need to ensure that you've a database on your Postgres server named `appdb` and a schema `app` in the database. Ensure your database credentials in `config/config.go` are matching with your credentials. Then try `cd server && go run main.go`.

Automatically program will create tables and sample data.

This project has been barely developed. We plan to complete this project in next 3 months, I will recommend you checking this project after 3 months. Closing this issue.
