### ISSUE TITLE
Create project boilerplate code (frontend)

### ISSUE THREAD

**Issue by bahetianjali** [haxxorsid/referralboard#7]
## Description
As a developer, I need boilerplate frontend code written in React typescript in a folder "client".

The code is a base to GET records from Golang endpoint localhost:5555/cards.

The code must hit the endpoint and display records on a page.

The code must also set up react-router with an additional hello world web page.

This boilerplate code must be modularized properly.

## Acceptance Criteria
- [x] Learn React and Golang, Postgres SQL (optional)
- [x] Write a boilerplate React code in a folder "client" using React (Typescript)
- [x] Read data from a GET endpoint (localhost:5555/cards) to display it in UI,
- [x] Setup another hello world web page and show it with a custom URL using react-router.
- [x] Modularize this code in proper folders.

**Comment by bahetianjali** [comment]
@haxxorsid check if all the description and acceptance criteria are ok

**Comment by haxxorsid** [comment]
@bahetianjali looks good to me. you can go ahead.
