### ISSUE TITLE
Create project boilerplate code (SQL)

### ISSUE THREAD

**Issue by Vineetkhadloya** [haxxorsid/referralboard#9]
As a developer, I want SQL code to be written in a folder “db”. 

Create a dummy table called “Cards” and add a dummy record. Create this table under schema “app”. 

Save the sql queries in the “db” folder.

## Acceptance Criteria
-	[x] Learn and setup Postgres SQL 14.1
-	[x] Write queries to create table and save these queries in “db” folder

**Comment by haxxorsid** [comment]
Pull request #12 merged. Closing the issue.
